server:
  port: 8000
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
#logging:
#  config: main/resources/logback-spring.xml
#  level:
#    luckyboy.mapper: trace
shareDb:
  db: share
  token: xxx
spring:
  application:
    name: share.luckyboy.cc
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:port/ashare?characterEncoding=utf-8&useSSL=false
    username: username
    password: password
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

